from datetime import date

VIDEOS = [
    {"id":"xlookup","title":"XLOOKUP", "type":"formula", "headers":["Employee","ID","Department","Salary"],
     "rows":[["Ahmed","E102","HSE",8500],["Sara","E103","HR",9200],["Ali","E104","Finance",10500],["Omar","E105","IT",11000]],
     "input_cell":"F4", "formula_cell":"F6", "formula":'=XLOOKUP(F4,B4:B7,D4:D7,"Not found")', "input":"E103", "result":"9200",
     "voice":"Need a salary from an employee ID? Use XLOOKUP. Type the ID, enter the formula, and Excel returns the matching salary instantly. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"FIND A VALUE\nFROM AN ID"),(4,9,"TYPE THE\nEMPLOYEE ID"),(9,17,"USE XLOOKUP\nTO FIND IT"),(17,24,"EXCEL RETURNS\nTHE MATCH"),(24,27,"RESULT = 9200"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"if_status","title":"IF Status", "type":"formula", "headers":["Task","Score","Status"],
     "rows":[["Safety","85",""],["Quality","62",""],["Training","91",""]],
     "input_cell":"E4", "formula_cell":"E6", "formula":'=IF(B4>=70,"PASS","FAIL")', "input":"85", "result":"PASS",
     "voice":"Turn a score into a clear status with IF. Compare the score with your target, then return PASS or FAIL automatically. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"TURN SCORES INTO\nPASS OR FAIL"),(4,9,"START WITH\nYOUR SCORE"),(9,17,"USE THE IF\nFUNCTION"),(17,24,"EXCEL DECIDES\nAUTOMATICALLY"),(24,27,"RESULT = PASS"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"sumif","title":"SUMIF", "type":"formula", "headers":["Product","Region","Sales"],
     "rows":[["Phone","UAE",1200],["Laptop","UAE",2500],["Tablet","KSA",900],["Monitor","UAE",1500]],
     "input_cell":"E4", "formula_cell":"E6", "formula":'=SUMIF(B4:B7,"UAE",C4:C7)', "input":"UAE", "result":"5200",
     "voice":"Need total sales for one region? SUMIF can do it in one formula. Set the region as your condition and Excel adds only matching sales. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"TOTAL SALES\nBY REGION"),(4,9,"CHOOSE YOUR\nREGION"),(9,17,"USE SUMIF\nAS THE FORMULA"),(17,24,"EXCEL ADDS\nMATCHING SALES"),(24,27,"RESULT = 5200"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"countif","title":"COUNTIF", "type":"formula", "headers":["Employee","Status"],
     "rows":[["Ahmed","Done"],["Sara","Pending"],["Ali","Done"],["Omar","Done"],["Hina","Pending"]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=COUNTIF(B4:B8,"Done")', "input":"Done", "result":"3",
     "voice":"Want to count completed tasks instantly? COUNTIF counts only the cells that match your condition. Use it for tasks, attendance, sales, or status lists. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"COUNT COMPLETED\nTASKS FAST"),(4,9,"SET YOUR\nSTATUS"),(9,17,"USE COUNTIF\nTO COUNT IT"),(17,24,"EXCEL COUNTS\nMATCHES"),(24,27,"RESULT = 3"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"iferror","title":"IFERROR", "type":"formula", "headers":["Item","Price","Qty"],
     "rows":[["Keyboard",80,2],["Mouse",45,3],["Monitor",700,1]],
     "input_cell":"E4", "formula_cell":"E6", "formula":'=IFERROR(B4/C4,"Check values")', "input":"Keyboard", "result":"40",
     "voice":"Stop ugly Excel errors from showing in your report. Wrap your formula with IFERROR and display a clean message when something goes wrong. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"HIDE EXCEL\nERRORS"),(4,9,"START WITH\nYOUR FORMULA"),(9,17,"WRAP IT WITH\nIFERROR"),(17,24,"SHOW A CLEAN\nRESULT"),(24,27,"NO UGLY ERRORS"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"average","title":"AVERAGE", "type":"formula", "headers":["Employee","Score"],
     "rows":[["Ahmed",80],["Sara",90],["Ali",70],["Omar",100]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=AVERAGE(B4:B7)', "input":"Scores", "result":"85",
     "voice":"Need the average of a score list? Use AVERAGE and select the cells. Excel calculates the mean instantly. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"GET THE\nAVERAGE FAST"),(4,9,"SELECT YOUR\nSCORES"),(9,17,"USE AVERAGE\nAS THE FORMULA"),(17,24,"EXCEL CALCULATES\nTHE MEAN"),(24,27,"RESULT = 85"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"max","title":"MAX", "type":"formula", "headers":["Employee","Sales"],
     "rows":[["Ahmed",1200],["Sara",2100],["Ali",1800],["Omar",1600]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=MAX(B4:B7)', "input":"Sales", "result":"2100",
     "voice":"Need the highest number in a list? MAX returns the largest value instantly. Select your range and Excel finds the top result. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"FIND THE\nHIGHEST VALUE"),(4,9,"SELECT YOUR\nNUMBER RANGE"),(9,17,"USE MAX\nAS THE FORMULA"),(17,24,"EXCEL FINDS\nTHE TOP VALUE"),(24,27,"RESULT = 2100"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"min","title":"MIN", "type":"formula", "headers":["Product","Price"],
     "rows":[["Phone",1800],["Tablet",900],["Watch",650],["Laptop",2500]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=MIN(B4:B7)', "input":"Price", "result":"650",
     "voice":"Need the lowest price in a list? MIN finds the smallest number instantly. Select your range and let Excel do the work. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"FIND THE\nLOWEST PRICE"),(4,9,"SELECT YOUR\nPRICE RANGE"),(9,17,"USE MIN\nAS THE FORMULA"),(17,24,"EXCEL FINDS\nTHE LOWEST"),(24,27,"RESULT = 650"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"sum","title":"SUM", "type":"formula", "headers":["Item","Amount"],
     "rows":[["Rent",3000],["Food",1200],["Fuel",500],["Bills",800]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=SUM(B4:B7)', "input":"Expenses", "result":"5500",
     "voice":"Add an entire column in seconds with SUM. Select the numbers, enter SUM, and Excel gives you the total. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"ADD A COLUMN\nIN SECONDS"),(4,9,"SELECT YOUR\nNUMBERS"),(9,17,"USE SUM\nAS THE FORMULA"),(17,24,"EXCEL CALCULATES\nTHE TOTAL"),(24,27,"RESULT = 5500"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"concat","title":"TEXTJOIN", "type":"formula", "headers":["First","Last"],
     "rows":[["Ahmed","Khan"],["Sara","Ali"],["Omar","Hassan"]],
     "input_cell":"D4", "formula_cell":"D6", "formula":'=TEXTJOIN(" ",TRUE,A4:B4)', "input":"First + Last", "result":"Ahmed Khan",
     "voice":"Combine text from multiple cells without manual typing. TEXTJOIN can join names, labels, or descriptions with a separator. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"COMBINE TEXT\nAUTOMATICALLY"),(4,9,"SELECT THE\nTEXT CELLS"),(9,17,"USE TEXTJOIN\nTO COMBINE"),(17,24,"EXCEL JOINS\nTHE VALUES"),(24,27,"RESULT = AHMED KHAN"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"index_match","title":"INDEX MATCH", "type":"formula", "headers":["Employee","ID","Salary"],
     "rows":[["Ahmed","E102",8500],["Sara","E103",9200],["Ali","E104",10500]],
     "input_cell":"E4", "formula_cell":"E6", "formula":'=INDEX(C4:C6,MATCH(E4,B4:B6,0))', "input":"E103", "result":"9200",
     "voice":"Here is a powerful lookup combination. MATCH finds the position, and INDEX returns the value from that position. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"POWERFUL\nLOOKUP COMBO"),(4,9,"TYPE THE\nEMPLOYEE ID"),(9,17,"MATCH FINDS\nTHE POSITION"),(17,24,"INDEX RETURNS\nTHE VALUE"),(24,27,"RESULT = 9200"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
    {"id":"checkbox_status","title":"Checkbox Status", "type":"checkbox", "headers":["Task","Done","Status"],
     "rows":[["Safety Inspection",None,""],["Daily Report",None,""],["Toolbox Talk",None,""],["Permit Check",None,""],["Training",None,""]],
     "voice":"Want clickable checkboxes in Excel? Insert a checkbox, link it to a cell, and let an IF formula turn TRUE or FALSE into a clean status. Follow Learn Verse for more Excel tips.",
     "captions":[(0,4,"ADD CLICKABLE\nCHECKBOXES"),(4,9,"CLICK A\nCHECKBOX"),(9,17,"LINK IT TO\nA CELL"),(17,24,"IF FORMULA\nUPDATES STATUS"),(24,27,"DONE = TRUE"),(27,30,"FOLLOW FOR MORE\nEXCEL TIPS")]},
]

def get_daily_videos(run_date: date, count=3):
    if count < 1: return []
    offset = ((run_date - date(2026,1,1)).days * 3) % len(VIDEOS)
    return [VIDEOS[(offset+i) % len(VIDEOS)] for i in range(count)]
