from __future__ import annotations

import datetime as dt

BASE_ROWS = [
    ["Ali", "Sales", 1200, "Completed"],
    ["Sara", "Sales", 850, "Pending"],
    ["Omar", "Support", 640, "Completed"],
    ["Noor", "Sales", 1500, "Completed"],
    ["Zain", "Support", 920, "Pending"],
    ["Maya", "Support", 710, "Completed"],
]

VIDEOS = [
    {
        "id": "countif",
        "title": "COUNTIF",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "Completed",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=COUNTIF(D5:D10,E10)',
        "voice": "Learn this Excel trick: COUNTIF counts cells that match a condition. Type a status, apply COUNTIF, and Excel instantly counts the matching rows.",
        "captions": [
            [0, 5, "1  Enter a condition"],
            [5, 12, "2  Type COUNTIF"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Excel counts the matches"],
        ],
        "hashtags": ["#Excel", "#ExcelTips", "#COUNTIF", "#LearnVerse"],
    },
    {
        "id": "sumif",
        "title": "SUMIF",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "Sales",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=SUMIF(B5:B10,E10,C5:C10)',
        "voice": "Use SUMIF to add only the values that meet your condition. Enter a department, apply SUMIF, and Excel totals the matching amounts.",
        "captions": [
            [0, 5, "1  Enter the criteria"],
            [5, 12, "2  Use SUMIF"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Excel returns the total"],
        ],
        "hashtags": ["#Excel", "#ExcelTips", "#SUMIF", "#LearnVerse"],
    },
    {
        "id": "xlookup",
        "title": "XLOOKUP",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "Noor",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=XLOOKUP(E10,A5:A10,C5:C10,"Not found")',
        "voice": "XLOOKUP makes searching a table easy. Enter a name, use XLOOKUP, and Excel returns the matching amount automatically.",
        "captions": [
            [0, 5, "1  Enter the name"],
            [5, 12, "2  Use XLOOKUP"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Excel finds the value"],
        ],
        "hashtags": ["#Excel", "#XLOOKUP", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "if",
        "title": "IF",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "1000",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=IF(E10>=1000,"PASS","REVIEW")',
        "voice": "The IF function lets Excel make a decision. Enter a number, compare it with a condition, and Excel returns the correct result.",
        "captions": [
            [0, 5, "1  Enter a number"],
            [5, 12, "2  Build an IF formula"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Excel makes the decision"],
        ],
        "hashtags": ["#Excel", "#IFFormula", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "average",
        "title": "AVERAGE",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=AVERAGE(C5:C10)',
        "voice": "AVERAGE calculates the mean of your numbers. Select the amount range, enter AVERAGE, and Excel gives you the result instantly.",
        "captions": [
            [0, 5, "1  Select your numbers"],
            [5, 12, "2  Type AVERAGE"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  See the average"],
        ],
        "hashtags": ["#Excel", "#AVERAGE", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "sum",
        "title": "SUM",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=SUM(C5:C10)',
        "voice": "SUM is the fastest way to total numbers in Excel. Select your amount range, use SUM, and Excel calculates the total for you.",
        "captions": [
            [0, 5, "1  Select the amount range"],
            [5, 12, "2  Type SUM"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Total calculated"],
        ],
        "hashtags": ["#Excel", "#SUM", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "max",
        "title": "MAX",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=MAX(C5:C10)',
        "voice": "MAX finds the largest number in a range. Select your values, enter MAX, and Excel instantly returns the highest amount.",
        "captions": [
            [0, 5, "1  Select the values"],
            [5, 12, "2  Type MAX"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Highest value found"],
        ],
        "hashtags": ["#Excel", "#MAX", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "min",
        "title": "MIN",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=MIN(C5:C10)',
        "voice": "MIN finds the smallest number in a range. Select your values, enter MIN, and Excel shows the lowest amount instantly.",
        "captions": [
            [0, 5, "1  Select the values"],
            [5, 12, "2  Type MIN"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Lowest value found"],
        ],
        "hashtags": ["#Excel", "#MIN", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "left",
        "title": "LEFT",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "LearnVerse",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=LEFT(E10,5)',
        "voice": "LEFT extracts characters from the beginning of text. Enter text, use LEFT with a number of characters, and Excel extracts exactly what you need.",
        "captions": [
            [0, 5, "1  Enter text"],
            [5, 12, "2  Use LEFT"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Text is extracted"],
        ],
        "hashtags": ["#Excel", "#LEFT", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "round",
        "title": "ROUND",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "1234.567",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=ROUND(E10,2)',
        "voice": "ROUND cleans decimal numbers. Enter a value, choose the number of decimal places, and Excel returns a neat rounded result.",
        "captions": [
            [0, 5, "1  Enter a decimal"],
            [5, 12, "2  Use ROUND"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Clean result"],
        ],
        "hashtags": ["#Excel", "#ROUND", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "concatenate",
        "title": "TEXT JOIN",
        "type": "formula",
        "headers": ["Name", "Department", "Amount", "Status"],
        "rows": BASE_ROWS,
        "input": "Excel",
        "input_cell": "E10",
        "formula_cell": "F12",
        "result_cell": "G12",
        "formula": '=TEXTJOIN(" - ",TRUE,E10,"LearnVerse")',
        "voice": "TEXTJOIN combines text with a separator. Enter a word, use TEXTJOIN, and Excel creates one clean text result automatically.",
        "captions": [
            [0, 5, "1  Enter text"],
            [5, 12, "2  Use TEXTJOIN"],
            [12, 20, "3  Press Enter"],
            [20, 29.5, "4  Text combined"],
        ],
        "hashtags": ["#Excel", "#TEXTJOIN", "#ExcelTips", "#LearnVerse"],
    },
    {
        "id": "checkbox",
        "title": "Interactive Checkboxes",
        "type": "checkbox",
        "headers": ["Task", "Owner", "Done", "Status"],
        "rows": [
            ["Safety review", "Ali", False, ""],
            ["Daily report", "Sara", False, ""],
            ["Client email", "Omar", False, ""],
            ["Site checklist", "Noor", False, ""],
            ["File upload", "Zain", False, ""],
        ],
        "voice": "Excel checkboxes can make task lists interactive. Click a checkbox, and the linked status changes automatically from pending to done.",
        "captions": [
            [0, 6, "1  Click a checkbox"],
            [6, 13, "2  Excel stores TRUE or FALSE"],
            [13, 21, "3  Status updates"],
            [21, 29.5, "4  Build interactive task lists"],
        ],
        "hashtags": ["#Excel", "#ExcelTips", "#Checkbox", "#LearnVerse"],
    },
]


def get_daily_videos(run_date: dt.date, count: int = 3):
    # Deterministic daily rotation so the same date always produces the same topics.
    start = run_date.toordinal() % len(VIDEOS)
    ordered = [VIDEOS[(start + i) % len(VIDEOS)] for i in range(len(VIDEOS))]
    return ordered[:max(1, min(count, len(ordered)))]
